#ifndef FACE_DETECTION_PLUGIN_GLOBAL_H
#define FACE_DETECTION_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FACE_DETECTION_PLUGIN_LIBRARY)
#  define FACE_DETECTION_PLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define FACE_DETECTION_PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FACE_DETECTION_PLUGIN_GLOBAL_H
